# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.ico"
    keywords: takooctopus takonoheya
    backgroundpic : "img/bg.jpg"

Intro:
    name: TAKONOHEYA
    slogan: "たこの部屋"
    HeadButton: TAKOOCTOPUS

Nav:
    Home_name: 主页
    is_use_categories : true 
    categories_name: 分类
    is_use_archives : false
    archives_name: 归档
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github: https://github.com/takooctopus
        tv: https://space.bilibili.com/499056
        home: https://takooctopus.github.io
        
    pages:
        简介: 
            link: "/about/"
        团队 :
            link: "/group/"
        翻译:
            link: "/translate/"
        图库 :
            link: "/gallery/"
        标签:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: TAKOOCTOPUS
    description: Student of TianJin University  
    pic_url: /images/me.jpg
    goto_ulr: ""

Gallery :
    title: Mr.TAKO 
    description: Pixiv藏图

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: false
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"



# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
